apiVersion: v1
kind: Service
metadata:
  name: idiom-finder-backend
  labels:
    app: idiom-finder-backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: idiom-finder-backend
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idiom-finder-backend
  labels:
    app: idiom-finder-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: idiom-finder-backend
  template:
    metadata:
      labels:
        app: idiom-finder-backend
    spec:
      containers:
        - image: scabbage/idiom-finder:latest
          name: idiom-finder
          env:
            - name: SANIC_RESPONSE_TIMEOUT
              value: "10"
          ports:
            - containerPort: 8000
              protocol: TCP
