apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: idiom-finder-backend
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":8000}]'
  labels:
    app: idiom-finder-backend
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: idiom-finder-backend
              servicePort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: idiom-finder-backend
  labels:
    app: idiom-finder-backend
spec:
  type: NodePort
  selector:
    app: idiom-finder-backend
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idiom-finder-backend
  labels:
    app: idiom-finder-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: idiom-finder-backend
  template:
    metadata:
      labels:
        app: idiom-finder-backend
    spec:
      containers:
        - image: scabbage/idiom-finder:latest
          name: idiom-finder
          env:
            - name: SANIC_RESPONSE_TIMEOUT
              value: "10"
          ports:
            - containerPort: 8000
              protocol: TCP
